# Generated by Django 4.1.9 on 2023-10-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RailApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_amount',
        ),
    ]
