# Generated by Django 5.0.1 on 2024-05-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RailApp', '0002_remove_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_id',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
    ]
