# Generated by Django 5.0.1 on 2024-05-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RailApp', '0003_ticket_paid_ticket_payment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_price_inr',
            new_name='amount',
        ),
    ]
