# Generated by Django 5.0.1 on 2024-07-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RailApp', '0004_rename_ticket_price_inr_ticket_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment_id',
        ),
    ]
