# Generated by Django 5.0.1 on 2024-07-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RailApp', '0005_remove_ticket_paid_remove_ticket_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='depart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='dest',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='start',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
