# Generated by Django 5.0.1 on 2024-07-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RailApp', '0006_train_depart_train_dest_train_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='depart',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
    ]
