# Generated by Django 5.0.1 on 2024-07-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RailApp', '0008_alter_train_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='depart',
            field=models.DateTimeField(null=True),
        ),
    ]
