# Generated by Django 5.0.1 on 2024-07-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RailApp', '0009_alter_train_depart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='depart',
        ),
    ]
